name: macOS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3